# Change these first
owner: EOSC-synergy # Your GitHub username
repo: eosc-perf-status # Your GitHub repository name

# Add your sites here
sites:
  - name: eosc-perf
    url: https://perf.test.fedcloud.eu
assignees: # Users to assign downtime issues (optional)
  - vykozlov
  - BorjaEst
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  ## c.n.a.m.e: perf-status.test.fedcloud.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /eosc-perf-status
  ## logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: eosc-perf status monitoring
  introTitle: "Status monitor for the EOSC-Perf site"
  introMessage: This page provides a real-time overview of the [EOSC-Perf](https://perf.test.fedcloud.eu) site.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
