# Change these first
owner: EOSC-synergy # Your GitHub username
repo: eosc-perf-status # Your GitHub repository name

# Add your sites here
sites:
  - name: eosc-perf
    url: https://perf.test.fedcloud.eu
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: perf-status.test.fedcloud.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  #-logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: eosc-perf status monitoring
  introTitle: "Status monitor for the EOSC-Perf site"
  introMessage: This page provides a real-time overview of the [EOSC-Perf](https://perf.test.fedcloud.eu) site.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
